AWSTemplateFormatVersion: 2010-09-09

Description: My First CloudFormation Template


Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-0022f774911c1d690"
      InstanceType: t2.micro
      KeyName: nova-pkey # replace the keypair      
      BlockDeviceMappings:
        -
          DeviceName: /dev/xvda
          Ebs:
            VolumeType: gp2            
            DeleteOnTermination: true
            VolumeSize: 8