# Export value

Parameters:
  SecurityGroupPorts:
    Description: Simple Description of a Number Parameter, with MinValue and MaxValue
    Type: Number
    AllowedValues: 
      - 80
      - 443
      - 22    

  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: Dev
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref VPC
      CidrBlock: 10.0.20.0/24
      Tags:
         - Key: Name
           Value: PubSub
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      VpcId: !Ref VPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: !Ref SecurityGroupPorts
        ToPort: !Ref SecurityGroupPorts
        CidrIp: !Ref SSHLocation
    

Outputs:
  SecurityGroupId:
    Description: sg Id value 
    Value: !GetAtt
      - SecurityGroup
      - GroupId
    Export: 
      Name: FemolaSg
  
  SubnetId:
    Description: subnet Id value
    Value: !GetAtt
      - Subnet
      - SubnetId
    Export: 
      Name: FemolaSub





      # Import value 


Resources:
  AppServer:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      ImageId: !Ref AMIID
      InstanceType: !Ref InstanceType
      SecurityGroupIds: 
        - !ImportValue FemolaSg
      SubnetId: !ImportValue FemolaSub
      BlockDeviceMappings:
        - DeviceName: "/dev/xvda"
          Ebs:
            VolumeSize: !Ref VolumeSize
            VolumeType: "gp2"
            DeleteOnTermination: true


Parameters:
  KeyName:
    Description: name of existing EC2 pairkey to enable SSH
    Type: AWS::EC2::KeyPair::KeyName
  
  AMIID:
    Description: EC2 Instance Image ID
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-ebs

  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro  
    AllowedValues:
      - t1.micro
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - m1.small
      - m1.medium
    ConstraintDescription: must be a valid EC2 instance type.

  VolumeSize:
    Description: EBS Volume size
    Type: Number
    Default: 8
    MinValue: 8
    MaxValue: 100
    ConstraintDescription: must be a number between 8 to 100 Gb 
